### ISSUE TITLE
Enhancement: Custom styling

### ISSUE THREAD

**Issue by jhildenbiddle** [pomdtr/val-town-playground#1]
Original discussion: https://github.com/val-town/val-town-product/discussions/88

---

It would be useful if the `vt-playground` web component styles could be customized via CSS custom properties. Customization efforts can be reduced by using [`color-mix()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix) to adjust unspecified colors as needed (e.g., make borders slightly lighter/darker than background color based on [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)).

Here is a basic example:

```css
/* Defaults */
:root {
  --vt-background-color: #eee;
  --vt-border-color: color-mix(in srgb, var(--vt-background-color) 93%, black);
}
```

 ```css
/* Custom styles */
:root {
  --vt-background-color: #222;
}
 ```
